---
title: Gids voor mijn land 1.0
hero_image: images/banner.png
description: Leer een ​​website maken
theme: red
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Opstarten
  - 
    title: Je eerste webpagina!
  - 
    title: Bepalen hoe het eruit ziet
  - 
    title: Afbeeldingen toevoegen
  - 
    title: Een kaart of video toevoegen
  - 
    title: Een lijst maken
  - 
    title: Links maken
  - 
    title: Meer pagina's toevoegen
  - 
    title: Navigeren door je website
  - 
    title: Een menubalk maken
  - 
    title: De menubalk opmaken
  - 
    title: Een tabel toevoegen
  - 
    title: Wat kun je verder nog doen?
