---
title: माझ्या देशाचे मार्गदर्शन १.०
hero_image: images/banner.png
description: वेब साईट बनवायला शिका
theme: red
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: परिचय
  - 
    title: सुरुवात अशी करा
  - 
    title: आपले पहिले webpage!
  - 
    title: ते कसे दिसेल हे नियंत्रित करण्याकरता
    completion:
      - engaged
  - 
    title: छायाचित्र जोडणे
  - 
    title: नकाशा किंव्हा व्हिडिओ जोडणे
  - 
    title: लीस्ट बनवणे
  - 
    title: लिंक तयार करणे
  - 
    title: आणखी पाने जोडणे
  - 
    title: आपल्या वेबसाईटवर नॅव्हिगेट करणे
  - 
    title: Menu bar बनवणे
  - 
    title: Menu bar ची शैली (स्टाईल) ठरवणे
  - 
    title: एक टेबल जोडणे
    completion:
      - internal
  - 
    title: परावर्तन
    quiz: true
  - 
    title: पुढे काय?
