---
title: Beginner HTML & CSS Sushi Cards
hero_image: images/banner.svg
description: Learn to make a website
theme: navy
duration: 1
listed: false
ingredient: false
copyedit: false
curriculum: 0, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: animals, humour, space, photography, music, games
technologies: html-css-javascript
site_areas: coderdojo
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: はじめに
- title: ウェブページをつくろう
- title: CSS（スタイルシート）を設定しよう
  completion:
  - engaged
- title: リストをつくってみよう
- title: 画像を追加する
- title: さらにページをつくろう
- title: リンクをつくろう
- title: ウェブサイトをナビゲートしよう
- title: メニューバーのスタイリング
- title: マップとビデオの追加
- title: テーブルの追加
- title: プロジェクトのダウンロード
  completion:
  - internal
