---
title: Guía para mi país 1.0
hero_image: images/banner.png
description: Aprende a hacer una página web
theme: rojo
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, proyectos
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Preparación
  - 
    title: '¡Tu primera página web!'
  - 
    title: Controlando cómo se ve
    completion:
      - engaged
  - 
    title: Añadiendo imágenes
  - 
    title: Añadiendo un mapa o video
  - 
    title: Haciendo una lista
  - 
    title: Creando enlaces
  - 
    title: Añadiendo más páginas
  - 
    title: Navegando por tu página web
  - 
    title: Haciendo un menú de tipo barra
  - 
    title: Dando estilo al menú de tipo barra
  - 
    title: Añadiendo una tabla
    completion:
      - internal
  - 
    title: Reflection
    quiz: true
  - 
    title: What next?
