---
title: Mein Länderführer 1.0
hero_image: images/banner.png
description: Lerne, wie du eine Website erstellst
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Erste Schritte
  - 
    title: Deine erste Website!
  - 
    title: Passe deine Seite an
  - 
    title: Bilder hinzufügen
  - 
    title: Karte oder Video hinzufügen
  - 
    title: Eine Liste erstellen
  - 
    title: Links erstellen
  - 
    title: Weitere Seiten hinzufügen
  - 
    title: Auf deiner Website navigieren
  - 
    title: Eine Menüleiste erstellen
  - 
    title: Die Menüleiste gestalten
  - 
    title: Eine Tabelle hinzufügen
  - 
    title: Wie geht es weiter?
