---
title: Ghidul țării mele 1.0
hero_image: images / banner.png
description: Află cum să creezi un website
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: Pentru început
  - 
    title: Prima ta pagină web!
  - 
    title: Controlul aspectului
  - 
    title: Adăugarea de imagini
  - 
    title: Adăugarea unei hărți sau video
  - 
    title: Crearea unei liste
  - 
    title: Crearea de legături
  - 
    title: Adăugarea mai multor pagini
  - 
    title: Navigarea pe website-ul tău
  - 
    title: Realizarea barei de meniu
  - 
    title: Stilizarea barei de meniu
  - 
    title: Adăugarea unui tabel
  - 
    title: Ce urmează?
