---
title: Guida al mio paese 1.0
hero_image: images / banner.png
description: Impara a creare un sito web
theme: rosso
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, progetti
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: Introduzione
  - 
    title: Prepararsi
  - 
    title: La tua prima pagina web!
  - 
    title: Controllare come appare
    completion:
      - engaged
  - 
    title: Aggiungere foto
  - 
    title: Aggiungere una mappa o un video
  - 
    title: Fare una lista
  - 
    title: Creare collegamenti
  - 
    title: Aggiungere più pagine
  - 
    title: Navigare nel tuo sito web
  - 
    title: Creare una barra dei menu
  - 
    title: Dare uno stile alla la barra dei menu
  - 
    title: Aggiungere una tabella
    completion:
      - internal
  - 
    title: Reflection
    quiz: true
  - 
    title: What next?
